### ISSUE TITLE
pnpm create fastjs@1.0.0-beta.2 windows 安装报错

### ISSUE THREAD

**Issue by yycdjh** [fastjs-team/core#113]
### What is the current behavior?

pnpm create fastjs@1.0.0-beta.2 error

? Enter the name of the app: fastjs-app
? Choose the init path for the app: Create a new directory with the app name
? Choose a template: Vanilla
? Choose a template type: JavaScript
? Choose a package manager: Use pnpm (recommended)

Creating project fastjs-app in ./fastjs-app

- Copying files...node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: cp -r D:\.pnpm-store\v3\tmp\dlx-33368\node_modules\.pnpm\create-fastjs@1.0.0-beta.2\node_modules\
create-fastjs\templates\vanilla/* D:\github\demo\fastjs-app
'cp' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'cp -r D:\\.pnpm-store\\v3\\tmp\\dlx-33368\\node_modules\\.pnpm\\create-fastjs@1.0.0-beta.2\\node_modules\\create
-fastjs\\templates\\vanilla/* D:\\github\\demo\\fastjs-app'
}

### What is the expected behavior?

正确安装

### Steps to reproduce the problem

windows
cmd
pnpm create fastjs@1.0.0-beta.2

### Confirmations

- [X] I'm using/tried the latest version of fastjs and the bug is still there
- [X] I have read the [Code of Conduct](https://docs.fastjs.dev/other/code-of-conduct.html)
- [X] I have read the [Issue Reporting Guidelines](https://github.com/fastjs-team/fastjs-next/blob/main/.github/contributing.md#issue-reporting)
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] I know that any inappropriate content may cause the maintainer to take action base on the [Code of Conduct](https://docs.fastjs.dev/other/code-of-conduct.html)

**Comment by xiaodong2008** [comment]
Fixed in `v1.0.0-beta.3`
