### ISSUE TITLE
Idea: 添加 tsdoc

### ISSUE THREAD

**Issue by FurryR** [fastjs-team/core#49]
写方法不写 TSDoc 导致读源码读得非常头疼。
是否考虑给所有方法和类添加 TSDoc？

**Comment by dy-xiaodong2022** [comment]
这些日后肯定是会加的，目前的话针对dom函数已经有ts类型展示了，分别是在Dom和DomList，后期会逐渐完善，如果你有兴趣一同编写文档，可以向xiaodong@indouyin.cn投递邮件，感谢你的意见
